### ISSUE TITLE
DockerHub builds failing

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/docker-studentenportal-base#1]
It looks like Python 3.7 builds are failing on Docker Hub:

https://hub.docker.com/repository/docker/studentenportal/base/builds

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

Not sure why they're cloning via SSH, but it looks like at some point their access was revoked on GitHub or so - when I try to configure the automated build, I get:

> Fetch source repositories failed.
>
> Error: Error trying to get GitHub user: 401 Client Error: Unauthorized for url: https://api.github.com/user.
>
> Connect a GitHub account to studentenportal to enable automated builds. If it is already connected, please re-link the source provider.

I can try to re-link the accounts of course - is it okay if I link @studentenportal-admin to Docker Hub?

**Comment by fabianhauser** [comment]
I'm not sure which user we originally connected to Docker Hub.

@studentenportal-admin is a bit quick'n'dirty, as it has access to private repos, i.e. pass (which is also encrypted) and the privat key in the old deploy repository (from which we will migrate away anyway).
So that should be okay IMHO.

I think read-only repo-access is still not possible with Dockerhub anyway, so please go ahead 🙂👍

**Comment by The-Compiler** [comment]
Re-linking fixed things! FWIW @studentenportal-admin already was linked anyways.
